(function(){
 document.addEventListener('DOMContentLoaded',()=>{
  const root=document.documentElement;
  function setView(list){root.classList.toggle('projects-list',list);document.getElementById('view-all').setAttribute('aria-pressed',String(list));document.getElementById('view-showcase').setAttribute('aria-pressed',String(!list));dispatchEvent(new Event('portfolio-view-change'));}
  document.getElementById('view-all')?.addEventListener('click',()=>setView(true));document.getElementById('view-showcase')?.addEventListener('click',()=>setView(false));
  document.getElementById('preview-motion')?.addEventListener('click',event=>{const playing=root.classList.toggle('preview-playing');event.currentTarget.setAttribute('aria-pressed',String(playing));event.currentTarget.textContent=playing?'Pause screenshot previews':'Play screenshot previews';dispatchEvent(new Event('portfolio-motion-change'));});
  const nodes={internet:['Internet','The external network edge shown in the lab topology. This diagram describes the environment; it does not test connectivity.'],router:['Router','The gateway between the internet connection and the lab network.'],pve0:['pve0 · Proxmox VE','A Lenovo ThinkCentre M710q with an Intel Core i5-7500, 16 GB DDR4, and a 2 TB SSD. Hosts the virtual machines shown here.'],vm01:['VM 01 · Debian','A Debian virtual machine hosted on pve0. The service list below describes the overall lab; individual service-to-VM assignments are not specified.'],vm02:['VM 02 · Debian','A second Debian virtual machine hosted on pve0, within the same self-hosted learning environment.'],vm03:['VM 03 · Ubuntu','An Ubuntu virtual machine hosted on pve0. The lab is used to explore deployment, monitoring, storage, and service communication.']};
  document.querySelectorAll('[data-node]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-node]').forEach(n=>n.setAttribute('aria-pressed',String(n===button)));const data=nodes[button.dataset.node],panel=document.getElementById('node-detail');panel.querySelector('h3').textContent=data[0];panel.querySelector('p').textContent=data[1];if(!root.classList.contains('motion-lite')){panel.getAnimations().forEach(a=>a.cancel());panel.animate([{clipPath:'inset(0 0 0 6%)',translate:'8px 0'},{clipPath:'inset(0)',translate:'0 0'}],{duration:320,easing:'cubic-bezier(.16,1,.3,1)'});}}));
  document.querySelectorAll('[data-enquiry]').forEach(link=>link.addEventListener('click',()=>{const subject=document.getElementById('contact-subject');subject.value=link.dataset.enquiry;setTimeout(()=>subject.focus({preventScroll:true}),100);}));
  // Keep background content and other dialogs inert while a modal is open.
  const dialogs=Array.from(document.querySelectorAll('[role="dialog"]'));
  function syncDialogs(){const open=dialogs.find(n=>n.classList.contains('open'));document.querySelectorAll('body>header,body>main,body>footer,.terminal-launcher,.back-to-top').forEach(n=>n.inert=!!open);dialogs.forEach(n=>n.inert=n!==open);}
  const observer=new MutationObserver(syncDialogs);dialogs.forEach(n=>observer.observe(n,{attributes:true,attributeFilter:['class']}));syncDialogs();
 });
})();
