const PROJECTS_DATA = [
  {
    id: 'homelab-os',
    name: 'HomeLab-OS',
    category: 'Infrastructure',
    shortDescription: 'A self-hosted Infrastructure Operating System that turns your homelab into a live Network Operations Center.',
    description: 'HomeLab OS turns your infrastructure into a live Network Operations Center. The dashboard renders a fleet of servers with CPU, memory, storage, temperature and network telemetry, a network topology map, an alert feed, and deep per-server detail views — all updated in real time. It ships in demo mode with a simulated six-host fleet and can switch to live Proxmox VE data and optionally HomeLab Agent integrations through environment configuration.',
    image: 'src/img/projects/homelab-os/homelab-os-preview.webp',
    scrollImage: 'src/img/projects/homelab-os/homelab-os-scroll.webp',
    imageFallback: 'src/img/projects/homelab-os/HomeLab-OS-Screenshot.png',
    logo: 'src/img/projects/homelab-os/HomeLab-OS-Logo.svg',
    technologies: ['React', 'TypeScript', 'Express', 'WebSocket', 'Tailwind', 'ECharts', 'SQLite', 'Docker'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/HomeLab-OS',
    docs: 'https://github.com/johnvexcoder/HomeLab-OS/blob/main/README.md',
    release: 'https://github.com/johnvexcoder/HomeLab-OS/releases',
    demo: null,
    openSource: true,
    featured: true,
    facts: ['v1.0.17', '2-second WebSocket telemetry', 'Proxmox + optional agent'],
    problemSolution: 'Built because conventional server dashboards often lacked enough control, visibility, security, or infrastructure context. Delivers central observability, server health visibility, topology understanding, system status, restricted account access, secure administration, and easy infrastructure monitoring.'
  },
  {
    id: 'homelab-agent',
    name: 'HomeLab-Agent',
    category: 'Infrastructure',
    shortDescription: 'The dedicated modular telemetry service that enriches HomeLab OS with node-local host, container, hardware, disk, and network data.',
    description: 'A modular, plugin-based telemetry agent built specifically for HomeLab OS. It runs on Linux hosts and reports the node-local information that the Proxmox API does not expose, including temperatures, fan speeds, SMART disk health, Docker containers, kernel details, services, and network health. Six isolated plugins auto-detect the host environment, collect at independent intervals, and securely report through the Agent Core without opening inbound ports.',
    image: null,
    logo: 'src/img/projects/homelab-agent/homelab-agent-icon.svg',
    visualType: 'service',
    visualLabel: 'Dedicated HomeLab OS telemetry service',
    technologies: ['TypeScript', 'Node.js', 'Linux', 'Docker', 'Proxmox'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/HomeLab-Agent',
    docs: 'https://github.com/johnvexcoder/HomeLab-Agent/blob/main/README.md',
    release: null,
    demo: null,
    openSource: true,
    featured: true,
    facts: ['v2.0.0', '6 modular plugins', '< 1% CPU · < 60 MB RAM'],
    problemSolution: 'Complements the Proxmox API with host-local telemetry while keeping collection modular, outbound-only, and resilient when optional tools or individual plugins are unavailable.'
  },
  {
    id: 'compressme',
    name: 'CompressMe',
    category: 'Software',
    shortDescription: 'A powerful, cross-platform image compression tool with a modern PySide6 GUI and full CLI.',
    description: 'A powerful, cross-platform image compression tool — modern PySide6 GUI plus full CLI. Batch-compress thousands of images, detect duplicates with perceptual hashing, preserve metadata, and generate detailed reports. Supports JPEG, PNG, WebP, AVIF, GIF, and RAW formats with optional external tool acceleration.',
    image: 'src/img/projects/compressme/compressme-screenshot.webp',
    imageFallback: 'src/img/projects/compressme/compressme-screenshot.png',
    logo: 'src/img/projects/compressme/compressme-icon.webp',
    logoFallback: 'src/img/projects/compressme/compressme-icon.png',
    technologies: ['Python', 'PySide6', 'Pillow', 'CLI', 'Desktop'],
    status: 'completed',
    github: 'https://github.com/johnvexcoder/CompressMe',
    docs: 'https://github.com/johnvexcoder/CompressMe/blob/main/README.md',
    release: 'https://github.com/johnvexcoder/CompressMe/releases',
    demo: null,
    openSource: true,
    featured: true,
    facts: ['Windows + Linux', 'GUI + CLI', 'Exact + perceptual dedupe'],
    problemSolution: 'Solves the pain of managing large photo libraries. Batch compression with parallel processing, duplicate detection to free up storage, and detailed reporting whether running from a GUI or a script.'
  },
  {
    id: 'movieflix',
    name: 'MovieFlix',
    category: 'Web',
    shortDescription: 'A self-hosted, private media streaming platform delivering a Netflix-inspired experience from your own storage.',
    description: 'A self-hosted, private media streaming platform. Scans local media folders, identifies movies and shows, fetches metadata from TMDB, analyzes codecs with FFprobe, and streams video over HTTP 206 partial-content requests. Includes multi-profile accounts, trial accounts, adaptive quality transcoding, subtitles, and a full administrative command center.',
    image: 'src/img/projects/movieflix/movieflix-preview.webp',
    scrollImage: 'src/img/projects/movieflix/movieflix-scroll.webp',
    imageFallback: 'src/img/projects/movieflix/movieflix-screenshot.png',
    logo: 'src/img/projects/movieflix/logo.svg',
    technologies: ['Next.js', 'React', 'TypeScript', 'Redis', 'SQLite', 'FFmpeg', 'Docker', 'TMDB'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/MovieFlix',
    docs: 'https://github.com/johnvexcoder/MovieFlix/blob/main/README.md',
    release: 'https://github.com/johnvexcoder/MovieFlix/releases',
    demo: 'https://movieflix.tailc31a5a.ts.net',
    openSource: true,
    featured: true,
    facts: ['v1.0.0', 'HTTP 206 streaming', 'On-demand FFmpeg transcoding'],
    problemSolution: 'Turns local and NAS media folders into a polished, private streaming platform. Accurate byte-range seeking, protection against bulk downloads, and full admin control all under your own infrastructure.'
  },
  {
    id: 'python-keybr',
    name: 'Python-Keybr',
    category: 'CLI',
    shortDescription: 'A terminal-based typing trainer inspired by keybr.com, built entirely in Python using the curses library.',
    description: 'A terminal-based typing trainer inspired by keybr.com, built in pure Python with the curses library. Features 6 practice modes, real-time WPM and accuracy tracking, persistent progress, adaptive letter unlocking, bigram tracking, and a professional keyboard diagnostic with NKRO monitoring.',
    image: null,
    logo: null,
    technologies: ['Python', 'curses', 'Terminal'],
    status: 'completed',
    github: 'https://github.com/johnvexcoder/Python-Keybr',
    docs: 'https://github.com/johnvexcoder/Python-Keybr/blob/master/README.md',
    release: 'https://github.com/johnvexcoder/Python-Keybr/releases',
    demo: null,
    openSource: true,
    featured: false,
    facts: ['v1.2.0', '6 practice modes', 'Adaptive letter unlocking'],
    problemSolution: 'Bringing an adaptive, keybr.com-style typing experience to the terminal. Tracks per-letter accuracy, unlocks letters progressively as you improve, and provides a full keyboard diagnostic tool.'
  },
  {
    id: 'distrozsh',
    name: 'DistroZSH',
    category: 'CLI',
    shortDescription: 'A lightweight, framework-free ZSH configuration delivering a native, professional terminal experience across Linux distributions.',
    description: 'A lightweight, framework-free ZSH configuration that delivers a native, professional terminal experience. Auto-detects the running distribution and applies per-distribution color themes. No framework, no plugin manager, no Nerd Font requirement. Four prompt layouts, smart command-not-found with typo suggestions, and a fully reversible installer.',
    image: null,
    logo: null,
    technologies: ['ZSH', 'Bash', 'Linux', 'Terminal'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/DistroZSH',
    docs: 'https://github.com/johnvexcoder/DistroZSH/blob/main/README.md',
    release: null,
    demo: null,
    openSource: true,
    featured: false,
    facts: ['ZSH 5.9+', '21 distro themes', 'Fully reversible installer'],
    problemSolution: 'Provides a clean, fast, distribution-aware ZSH experience without the bloat of frameworks like Oh My Zsh. The prompt adopts the color of your distribution while keeping one consistent, native layout.'
  },
  {
    id: 'starbucks-portal',
    name: 'Starbucks Portal',
    category: 'Web',
    shortDescription: 'An unofficial UI concept / practice project exploring modern portal design.',
    description: 'An unofficial Starbucks portal concept built for fun and as an experiment in modern portal design. This is a UI concept / practice project only — not affiliated with or commissioned by Starbucks. It explores premium design patterns, modern layouts, and polished interactions.',
    image: 'src/img/projects/starbucks-portal/startbucks-portal-screenshot.webp',
    imageFallback: 'src/img/projects/starbucks-portal/startbucks-portal-screenshot.png',
    logo: 'src/img/projects/starbucks-portal/starbucks-icon.webp',
    logoFallback: 'src/img/projects/starbucks-portal/starbucks-icon.png',
    technologies: ['HTML', 'CSS', 'JavaScript', 'UI/UX'],
    status: 'concept',
    github: 'https://github.com/johnvexcoder/johnvexcoder.github.io/tree/main/projects/Starbucks-Login',
    docs: 'https://github.com/johnvexcoder/johnvexcoder.github.io/tree/main/projects/Starbucks-Login#readme',
    release: null,
    demo: null,
    openSource: false,
    featured: false,
    facts: ['UI concept', 'Responsive interface study', 'Not affiliated with Starbucks'],
    problemSolution: 'An experiment in modern portal design — built mainly for fun and to practice building polished, responsive web interfaces. Not an official Starbucks product.',
    disclaimer: 'Unofficial Concept Project'
  }
];

const UPCOMING_PROJECTS = [
  {
    name: 'EmailBlast - SMTP',
    icon: 'mail',
    status: 'concept',
    tagline: 'Planned',
    description: 'A customizable enterprise email campaign management system designed for sending templated emails to contact groups, managing multiple SMTP senders, tracking delivery status, and running paced campaigns automatically in the background.',
    capabilities: ['Templated emails', 'Multiple SMTP senders', 'Delivery tracking', 'Automated campaigns']
  },
  {
    name: 'VaultNote',
    icon: 'lock',
    status: 'concept',
    tagline: 'In Development',
    description: 'A privacy-focused web application for storing notes, documents, credentials, and important information in an organized and encrypted workspace.',
    capabilities: ['Categories', 'Search', 'Tagging', 'Attachments', 'Encryption']
  },
  {
    name: 'InvoiceFlow',
    icon: 'file',
    status: 'concept',
    tagline: 'Planned',
    description: 'A modern client and invoice management platform for freelancers and small businesses.',
    capabilities: ['Quotations', 'Invoices', 'Payment tracking', 'Client records', 'Document generation']
  }
];
