const PROJECTS_DATA = [
  {
    id: 'homelab-os',
    name: 'HomeLab-OS',
    category: 'Infrastructure',
    shortDescription: 'A self-hosted Infrastructure Operating System that turns your homelab into a live Network Operations Center.',
    description: 'HomeLab OS turns your infrastructure into a live Network Operations Center. The dashboard renders a fleet of servers with CPU, memory, storage, temperature and network telemetry, a network topology map, an alert feed, and deep per-server detail views — all updated in real time. It ships in demo mode with a simulated six-host fleet and can switch to live Proxmox VE data and optionally HomeLab Agent integrations through environment configuration.',
    image: 'src/img/projects/homelab-os/homelab-os-preview.webp',
    scrollImage: 'src/img/projects/homelab-os/homelab-os-scroll.webp',
    imageFallback: 'src/img/projects/homelab-os/HomeLab-OS-Screenshot.png',
    logo: 'src/img/projects/homelab-os/HomeLab-OS-Logo.svg',
    technologies: ['React', 'TypeScript', 'Express', 'WebSocket', 'Tailwind', 'ECharts', 'SQLite', 'Docker'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/HomeLab-OS',
    docs: 'https://github.com/johnvexcoder/HomeLab-OS/blob/main/README.md',
    release: 'https://github.com/johnvexcoder/HomeLab-OS/releases',
    demo: null,
    openSource: true,
    featured: true,
    facts: ['v1.0.17', '2-second WebSocket telemetry', 'Proxmox + optional agent'],
    problemSolution: 'Built because conventional server dashboards often lacked enough control, visibility, security, or infrastructure context. Delivers central observability, server health visibility, topology understanding, system status, restricted account access, secure administration, and easy infrastructure monitoring.'
  },
  {
    id: 'homelab-agent',
    name: 'HomeLab-Agent',
    category: 'Infrastructure',
    shortDescription: 'The dedicated modular telemetry service that enriches HomeLab OS with node-local host, container, hardware, disk, and network data.',
    description: 'A modular, plugin-based telemetry agent built specifically for HomeLab OS. It runs on Linux hosts and reports the node-local information that the Proxmox API does not expose, including temperatures, fan speeds, SMART disk health, Docker containers, kernel details, services, and network health. Six isolated plugins auto-detect the host environment, collect at independent intervals, and securely report through the Agent Core without opening inbound ports.',
    image: null,
    logo: 'src/img/projects/homelab-agent/homelab-agent-icon.svg',
    visualType: 'service',
    visualLabel: 'Dedicated HomeLab OS telemetry service',
    technologies: ['TypeScript', 'Node.js', 'Linux', 'Docker', 'Proxmox'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/HomeLab-Agent',
    docs: 'https://github.com/johnvexcoder/HomeLab-Agent/blob/main/README.md',
    release: null,
    demo: null,
    openSource: true,
    featured: true,
    facts: ['v2.0.0', '6 modular plugins', '< 1% CPU · < 60 MB RAM'],
    problemSolution: 'Complements the Proxmox API with host-local telemetry while keeping collection modular, outbound-only, and resilient when optional tools or individual plugins are unavailable.'
  },
  {
    id: 'compressme',
    name: 'CompressMe',
    category: 'Software',
    shortDescription: 'A powerful, cross-platform image compression tool with a modern PySide6 GUI and full CLI.',
    description: 'A powerful, cross-platform image compression tool — modern PySide6 GUI plus full CLI. Batch-compress thousands of images, detect duplicates with perceptual hashing, preserve metadata, and generate detailed reports. Supports JPEG, PNG, WebP, AVIF, GIF, and RAW formats with optional external tool acceleration.',
    image: 'src/img/projects/compressme/compressme-screenshot.webp',
    imageFallback: 'src/img/projects/compressme/compressme-screenshot.png',
    logo: 'src/img/projects/compressme/compressme-icon.webp',
    logoFallback: 'src/img/projects/compressme/compressme-icon.png',
    technologies: ['Python', 'PySide6', 'Pillow', 'CLI', 'Desktop'],
    status: 'completed',
    github: 'https://github.com/johnvexcoder/CompressMe',
    docs: 'https://github.com/johnvexcoder/CompressMe/blob/main/README.md',
    release: 'https://github.com/johnvexcoder/CompressMe/releases',
    demo: null,
    openSource: true,
    featured: true,
    facts: ['Windows + Linux', 'GUI + CLI', 'Exact + perceptual dedupe'],
    problemSolution: 'Solves the pain of managing large photo libraries. Batch compression with parallel processing, duplicate detection to free up storage, and detailed reporting whether running from a GUI or a script.'
  },
  {
    id: 'movieflix',
    name: 'MovieFlix',
    category: 'Web',
    shortDescription: 'A self-hosted, private media streaming platform delivering a Netflix-inspired experience from your own storage.',
    description: 'A self-hosted, private media streaming platform. Scans local media folders, identifies movies and shows, fetches metadata from TMDB, analyzes codecs with FFprobe, and streams video over HTTP 206 partial-content requests. Includes multi-profile accounts, trial accounts, adaptive quality transcoding, subtitles, and a full administrative command center.',
    image: 'src/img/projects/movieflix/movieflix-cover.webp',
    scrollImage: 'src/img/projects/movieflix/movieflix-scroll.webp',
    imageFallback: 'src/img/projects/movieflix/movieflix-ss.png',
    logo: 'src/img/projects/movieflix/logo.svg',
    technologies: ['Next.js', 'React', 'TypeScript', 'Redis', 'SQLite', 'FFmpeg', 'Docker', 'TMDB'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/MovieFlix',
    docs: 'https://github.com/johnvexcoder/MovieFlix/blob/main/README.md',
    release: 'https://github.com/johnvexcoder/MovieFlix/releases',
    demo: 'https://movieflix.tailc31a5a.ts.net',
    openSource: true,
    featured: true,
    facts: ['v1.0.0', 'HTTP 206 streaming', 'On-demand FFmpeg transcoding'],
    problemSolution: 'Turns local and NAS media folders into a polished, private streaming platform. Accurate byte-range seeking, protection against bulk downloads, and full admin control all under your own infrastructure.'
  },
  {
    id: 'python-keybr',
    name: 'Python-Keybr',
    category: 'CLI',
    shortDescription: 'A terminal-based typing trainer inspired by keybr.com, built entirely in Python using the curses library.',
    description: 'A terminal-based typing trainer inspired by keybr.com, built in pure Python with the curses library. Features 6 practice modes, real-time WPM and accuracy tracking, persistent progress, adaptive letter unlocking, bigram tracking, and a professional keyboard diagnostic with NKRO monitoring.',
    image: null,
    logo: null,
    technologies: ['Python', 'curses', 'Terminal'],
    status: 'completed',
    github: 'https://github.com/johnvexcoder/Python-Keybr',
    docs: 'https://github.com/johnvexcoder/Python-Keybr/blob/master/README.md',
    release: 'https://github.com/johnvexcoder/Python-Keybr/releases',
    demo: null,
    openSource: true,
    featured: false,
    facts: ['v1.2.0', '6 practice modes', 'Adaptive letter unlocking'],
    problemSolution: 'Bringing an adaptive, keybr.com-style typing experience to the terminal. Tracks per-letter accuracy, unlocks letters progressively as you improve, and provides a full keyboard diagnostic tool.'
  },
  {
    id: 'distrozsh',
    name: 'DistroZSH',
    category: 'CLI',
    shortDescription: 'A lightweight, framework-free ZSH configuration delivering a native, professional terminal experience across Linux distributions.',
    description: 'A lightweight, framework-free ZSH configuration that delivers a native, professional terminal experience. Auto-detects the running distribution and applies per-distribution color themes. No framework, no plugin manager, no Nerd Font requirement. Four prompt layouts, smart command-not-found with typo suggestions, and a fully reversible installer.',
    image: null,
    logo: null,
    technologies: ['ZSH', 'Bash', 'Linux', 'Terminal'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/DistroZSH',
    docs: 'https://github.com/johnvexcoder/DistroZSH/blob/main/README.md',
    release: null,
    demo: null,
    openSource: true,
    featured: false,
    facts: ['ZSH 5.9+', '21 distro themes', 'Fully reversible installer'],
    problemSolution: 'Provides a clean, fast, distribution-aware ZSH experience without the bloat of frameworks like Oh My Zsh. The prompt adopts the color of your distribution while keeping one consistent, native layout.'
  },
  {
    id: 'starbucks-portal',
    name: 'Starbucks Login',
    category: 'Web',
    shortDescription: 'An unofficial Starbucks-inspired login page demo — a functional UI concept with working form validation.',
    description: 'An unofficial Starbucks-inspired login page built as a fun UI concept and practice project. The demo runs entirely in the browser with client-side form handling and demo credentials, and is not affiliated with or commissioned by Starbucks.',
    image: 'src/img/projects/starbucks-portal/startbucks-portal-screenshot.webp',
    imageFallback: 'src/img/projects/starbucks-portal/startbucks-portal-screenshot.png',
    logo: 'src/img/projects/starbucks-portal/starbucks-icon.webp',
    logoFallback: 'src/img/projects/starbucks-portal/starbucks-icon.png',
    technologies: ['HTML', 'CSS', 'JavaScript', 'UI/UX'],
    status: 'demo',
    github: null,
    docs: null,
    release: null,
    demo: 'projects/starbucks-login/',
    openSource: false,
    featured: false,
    facts: ['Live demo', 'Demo login: customer@email.com', 'Not affiliated with Starbucks'],
    problemSolution: 'A working, client-side login page demo built purely for fun and to practice building polished, responsive web interfaces. Not an official Starbucks product.',
    disclaimer: 'Unofficial Concept Project — Live Demo'
  },
  {
    id: 'smart-expense',
    name: 'Smart Expense Visualizer',
    category: 'Web',
    shortDescription: 'An interactive expense-tracking dashboard with Chart.js visualization — try it live right in the browser.',
    description: 'A browser-based expense-tracking demo using JavaScript, Tailwind CSS, and Chart.js. Add expenses, organize them by category, and watch a live pie chart update as you go. All data is persisted only in your browser via localStorage — no server or database — which makes it perfect as a hands-on portfolio demo. Includes dark/light theme, spending summary cards, custom categories, and a sortable transactions table.',
    image: 'src/img/projects/smart-expenses/smart-expense-preview.webp',
    imageFallback: 'src/img/projects/smart-expenses/smart-expenses.png',
    logo: 'src/img/projects/smart-expenses/smart-expense-icon.webp',
    logoFallback: 'src/img/projects/smart-expenses/smart-expense-icon.png',
    technologies: ['JavaScript', 'Chart.js', 'Tailwind', 'localStorage'],
    status: 'demo',
    github: null,
    docs: null,
    release: null,
    demo: 'projects/smart-expense/',
    openSource: false,
    featured: false,
    facts: ['Live demo', 'localStorage (no database)', 'Dark/light theme'],
    problemSolution: 'Makes tracking expenses visual and immediate. The whole app runs client-side in the browser, so anyone can try it live without any backend, database, or setup.',
    disclaimer: 'Live Demo — Data stays in your browser'
  },
  {
    id: 'monthsary',
    name: 'Monthsary',
    category: 'Web',
    shortDescription: 'A heartfelt 15th monthsary dedication website — a countdown of time together, a love timeline, photo galleries, and letters.',
    description: 'A personal anniversary website dedicated to a 15th monthsary. Features a live time-together counter (days, months, hours, minutes, seconds since May 21 2025), a love timeline, photo museums, photobooth strips, video moments, and handwritten letters. Built with a warm, romantic design and subtle interactions.',
    image: 'src/img/projects/monthsary/monthsary-preview.webp',
    scrollImage: 'src/img/projects/monthsary/monthsary-scroll.webp',
    imageFallback: 'src/img/projects/monthsary/monthsary-preview.webp',
    logo: 'src/img/projects/monthsary/monthsary-icon.webp',
    logoFallback: 'src/img/projects/monthsary/monthsary-icon.webp',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    status: 'active',
    github: null,
    docs: null,
    release: null,
    demo: 'https://15th-monthsary.netlify.app/',
    openSource: false,
    featured: true,
    facts: ['Live site', 'Time together counter', 'Photo galleries + letters'],
    problemSolution: 'A personal dedication site to celebrate and preserve an anniversary — every moment together counted, remembered, and expressed with love.',
    disclaimer: 'Personal Project'
  },
  {
    id: 'johnvex-winops',
    name: 'JohnVex-WinOps',
    category: 'Infrastructure',
    shortDescription: 'Enterprise Windows Administration Suite — a modular PowerShell engine for health, licensing, and system operations.',
    description: 'JohnVex WinOps is an enterprise Windows administration suite built on a modular Windows PowerShell 5.1 engine. It ships Community, Professional, and Enterprise edition boundaries, enterprise-safe licensing diagnostics, system inventory, health auditing, network diagnostics, DISM and SFC handlers, a declarative operation catalog with a fixed code allowlist, dry-run planning with explicit risk acceptance, verified registry writes, operation journals, rollback, and structured JSONL session logging. Preserves the audited Win11Max.bat as the Community compatibility engine.',
    image: 'src/img/projects/winops/winops-preview.webp',
    imageFallback: 'src/img/projects/winops/winops-preview.webp',
    logo: 'src/img/projects/winops/winops-icon.webp',
    logoFallback: 'src/img/projects/winops/winops-icon.webp',
    technologies: ['PowerShell', 'Windows', 'Security', 'Automation'],
    status: 'active',
    github: 'https://github.com/johnvexcoder/JohnVex-WinOps',
    docs: 'https://github.com/johnvexcoder/JohnVex-WinOps/blob/main/README.md',
    release: 'https://github.com/johnvexcoder/JohnVex-WinOps/releases',
    demo: null,
    openSource: true,
    featured: true,
    facts: ['v3.0.0', 'PowerShell 5.1', 'Community/Pro/Enterprise'],
    problemSolution: 'Administrative Windows operations often sprawl across ad-hoc scripts. WinOps centralizes them behind a vetted, declarative, and safely executable engine with rollback and journals.',
    disclaimer: null
  }
];

const UPCOMING_PROJECTS = [
  {
    name: 'EmailBlast - SMTP',
    icon: 'mail',
    status: 'concept',
    tagline: 'Planned',
    description: 'A customizable enterprise email campaign management system designed for sending templated emails to contact groups, managing multiple SMTP senders, tracking delivery status, and running paced campaigns automatically in the background.',
    capabilities: ['Templated emails', 'Multiple SMTP senders', 'Delivery tracking', 'Automated campaigns']
  },
  {
    name: 'VaultNote',
    icon: 'lock',
    status: 'concept',
    tagline: 'In Development',
    description: 'A privacy-focused web application for storing notes, documents, credentials, and important information in an organized and encrypted workspace.',
    capabilities: ['Categories', 'Search', 'Tagging', 'Attachments', 'Encryption']
  },
  {
    name: 'InvoiceFlow',
    icon: 'file',
    status: 'concept',
    tagline: 'Planned',
    description: 'A modern client and invoice management platform for freelancers and small businesses.',
    capabilities: ['Quotations', 'Invoices', 'Payment tracking', 'Client records', 'Document generation']
  }
];
